config/routes.rb
Ticketee::Application.routes.draw do
  get "users/index"

  devise_for :users

  root :to => "projects#index"
  
  resources :projects do 
    resources :tickets
  end
  

  namespace :admin do 
    root :to => "base#index" 
    resources :users
  end
  
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing, :polymorphic => true
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, :presence => true
  
  has_many :permissions, :as => :thing 
  scope :readable_by, lambda { |user|
    joins(:permissions).where(:permissions => { :action => "view", 
                                                :user_id => user.id })
  }  
  
  has_many :tickets

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  
  validates :title, :presence => true 
  validates :description, :presence => true, :length => { :minimum => 10 }
  
  belongs_to :project 
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tickets
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def to_s 
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController 
  
  before_filter :authorize_admin!
  
  def index
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all(:order => "email") 
  end

  def show 
  end
  
  def new 
    @user = User.new
  end
  
  def create 
    @user = User.new(params[:user]) 
    set_admin
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path 
    else
      flash[:alert] = "User has not been created."
      render :action => "new" 
    end
  end
  
  def edit
  end
  
  def update 
    if params[:user][:password].blank? 
      params[:user].delete(:password) 
      params[:user].delete(:password_confirmation)
    end
    
    set_admin
    if @user.update_attributes(params[:user])
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path 
    else
      flash[:alert] = "User has not been updated."
      render :action => "edit" 
    end
  end
  
  def destroy 
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!" 
    else
      @user.destroy
      flash[:notice] = "User has been deleted." 
    end
    redirect_to admin_users_path 
  end
  
  private 
    def find_user
      @user = User.find(params[:id]) 
    end
    
    def set_admin 
      @user.admin = params[:user][:admin] == "1"
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
    def authorize_admin! 
      authenticate_user! 
      unless current_user.admin?
        flash[:alert] = "You must be an admin to do that."
        redirect_to root_path 
      end
    end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
before_filter :authorize_admin!, :except => [:index, :show] 
before_filter :authenticate_user!, :only => [:show] 
before_filter :find_project, :only => [:show, :edit, :update, :destroy]
  
  def index
    @projects = Project.all
  end
  
  def new
    @project = Project.new
  end

  def create 
    @project = Project.new(params[:project]) 
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project 
    else
      flash[:alert] = "Project has not been created."
      render :action => "new" 
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update 
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project 
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit" 
    end
  end 
  
  def destroy 
    @project.destroy 
    flash[:notice] = "Project has been deleted." 
    redirect_to projects_path
  end
   
  private 
    def find_project
      @project = if current_user.admin? 
        Project.find(params[:id])
      else 
        Project.readable_by(current_user).find(params[:id])
      end
      
      rescue ActiveRecord::RecordNotFound 
        flash[:alert] = "The project you were looking" +
          " for could not be found." 
        redirect_to projects_path
      end
   
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_project
  before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]
  
  def new 
    @ticket = @project.tickets.build
  end
  
  def create 
    @ticket = @project.tickets.build(params[:ticket].merge!(:user => current_user)) 
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket] 
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new" 
    end
  end
  
  def edit 
  end

  def update 
    if @ticket.update_attributes(params[:ticket])
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket] 
    else
      flash[:alert] = "Ticket has not been updated."
      render :action => "edit" 
    end
  end
    
  def destroy 
    @ticket.destroy 
    flash[:notice] = "Ticket has been deleted." 
    redirect_to @project
  end
      
  private 
    def find_project
      @project = Project.find(params[:project_id]) 
    end
    
    def find_ticket 
      @ticket = @project.tickets.find(params[:id])
    end
    
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper 
  
  def title(*parts)
    @title = (parts << "Ticketee").join(" - ") unless parts.empty? 
    @title || "Ticketee" 
  end
  
  def admins_only(&block)
    block.call if current_user.try(:admin?)
    nil 
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/base/index.html.erb
<%= link_to "Users", admin_users_path %> 
Welcome to Ticketee's Admin Lounge. Please enjoy your stay.

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %> 
	<%= f.error_messages %> 
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %> 
	</p>
	<p> 
		<%= f.label :password %> 
		<%= f.password_field :password %>
	</p>
	<p> 
		<%= f.label :password_confirmation %> 
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.check_box :admin %> 
		<%= f.label :admin, "Is an admin?" %>
	</p>
	<%= f.submit %> 
<% end %>

app/views/admin/users/edit.html.erb
<%= render "form" %>

app/views/admin/users/index.html.erb
<%= link_to "New User", new_admin_user_path %> 
<ul>
	<% @users.each do |user| %> 
		<li><%= link_to user, [:admin, user] %></li>
	<% end %> 
</ul>

app/views/admin/users/new.html.erb
<%= render "form" %>

app/views/admin/users/show.html.erb
<h2><%= @user %></h2> 
<%= link_to "Edit", edit_admin_user_path(@user) %>
<%= link_to "Delete", admin_user_path(@user), 
	:method => :delete, 
	:confirm => "Are you sure you want to delete this user?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
	<title><%= title %></title>
  	<%= stylesheet_link_tag :all %>
  	<%= javascript_include_tag :defaults %>
  	<%= csrf_meta_tag %>
</head>
<body>

<% flash.each do |key, value| %> 
	<div class='flash' id='<%= key %>'>
		<%= value %> 
	</div>
<% end %>

<h1><%= link_to "Ticketee", root_path %></h1>

<%= admins_only do %> 
	<%= link_to "Admin", admin_root_path %>
<% end %>

<nav> 
	<% if !user_signed_in? %> 
		<%= link_to "Sign up", new_user_registration_path %>
		<%= link_to "Sign in", new_user_session_path %>
	<% else %> 
		Signed in as <%= current_user.email %>
	<% end %>
</nav>
	
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %> 
	<p>
	<%= f.error_messages %>
	<%= f.label :name %>
	<%= f.text_field :name %> 
	</p>
	<%= f.submit %> 
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2> 
<%= render "form" %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>
<h2>Projects</h2> 
<ul>
	<% @projects.each do |project| %> 
		<%= admins_only do %> 
			<%= link_to "New Project", new_project_path %>
		<% end %>
	<% end %> 
</ul>

app/views/projects/new.html.erb
<h2>New project</h2> 
<%= render "form" %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<% title(@project.name, "Projects") %>

<menu> 
	<%= admins_only do %> 
		<%= link_to "Edit", edit_project_path(@project) %> 
		<%= link_to "Delete", project_path(@project), 
			:method => :delete,
			:confirm => "Are you sure you want to delete this project?" %>
	<% end %>

	<%= link_to "New Ticket", new_project_ticket_path(@project) %>	
</menu>

<ul id='tickets'> 
	<% @project.tickets.each do |ticket| %>
		<li>#<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %></li> 
	<% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %> 
	<%= f.error_messages %> 
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %> 
	</p>
	<p> 
		<%= f.label :description %><br> 
		<%= f.text_area :description %>
	</p>
	<%= f.submit %> 
<% end %>
	

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2> 
<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2> 
<%= render "form" %>

app/views/tickets/show.html.erb
<div id='ticket'> 
	<h2><%= @ticket.title %></h2>
	
	<menu> 
		<%= link_to "Edit", [:edit, @project, @ticket] %>
		<%= link_to "Delete", [@project, @ticket], 
			:method => :delete, 
			:confirm => "Are you sure you want to delete this ticket?" %>
	</menu> 
	
	<small>Created by <%= @ticket.user.email %></small>
	<%= simple_format(@ticket.description) %>
</div>